listeners:
  replantCrops: true
  craftingTableDiscoverRecipes: true
  craftingTableCraftFromNearbyInventories: true
warn:
  beforeToolBreak: true
  beforeToolBreakMessage: "&cYour tool is about to break!"
others:
  collectCraftingHistory: true